name: VanillaPlus
version: '${version}'
main: BK.VanillaPlus.VanillaPlus
api-version: '1.21'
load: POSTWORLD

commands:
  vp-reload:
    description: Reloads the VanillaPlus configuration.
    permission: VanillaPlus.reload
    usage: /vp-reload
  vp-setspawn:
    description: Set the world spawn to your current location
    permission: VanillaPlus.setspawn
    usage: /vp-setspawn
  vp-spawn:
    description: Teleports player to the spawn
    permission: VanillaPlus.spawn
    usage: /vp-spawn
  vp-inspect-stash:
    description: Inspects a player's virtual stash.
    permission: VanillaPlus.inspect_stash
    usage: /vp-inspect-stash <player>
  vp-ram-stashes:
    description: Shows stashes in ram.
    permission: VanillaPlus.ram_stashes
    usage: /vp-ram-stashes
  vp-overflow:
    description: Changes the overflow setting for this player.
    permission: VanillaPlus.overflow
    usage: /vp-overflow <on|off>
  vp-stash:
    description: Opens your stash.
    permission: VanillaPlus.stash
    usage: /vp-stash
  vp-hud:
    description: Toggle your scoreboard HUD elements
    permission: VanillaPlus.hud
    usage: /vp-hud <deaths | sleep | ping> [ 0 | 1 | 2 ]
  vp-world-age:
    description: Show world age and play time of the player using it
    permission: VanillaPlus.world_age
    usage: /vp-world-age
  vp-create-warp:
    description: Create a new warp
    permission: VanillaPlus.create_warp
    usage: /vp-create-warp <warp name>
  vp-delete-warp:
    description: Delete a warp
    permission: VanillaPlus.delete_warp
    usage: /vp-delete-warp <warp name>
  vp-warp:
    description: Warp to a location
    permission: VanillaPlus.warp
    usage: /vp-warp <warp name>
  vp-warp-list:
    description: Returns a list of all warps
    permission: VanillaPlus.warp_list
    usage: /vp-warp-list
  vp-chunkload:
    description: Loads a chunk area around the player
    permission: VanillaPlus.chunkload
    usage: /vp-chunkload